---
title: "CIMICE Web App"
output: html_document
runtime: shiny
---

This is a simple web interface to easly use CIMICE tool on your datasets. Copy your dataset in the text area, choose the best parameters for 
your analisys and run the program by pressing the "Load new Dataset" button.

```{r, echo=F}
knitr::opts_chunk$set(echo = F, fig.align="center")
```

```{r, error=F, message=F, results = "hide"}
# Dataframe manipulation
library(dplyr) 
# Plot display
library(ggplot2)
# Improved string operations
library(glue)
# Dataframe manipulation
library(tidyr)
# Graph data management
library(igraph)
# Remove transitive edges on o graph
library(nem)
# Interactive graph visualization
library(networkD3)
# Interactive graph visualization
library(visNetwork)
# Correlation plot visualization
library(ggcorrplot)
# Functional R programming
library(purrr)
# Graph Visualization
library(ggraph)
# Graph manipulation/visualization
library(tidygraph)
# purrr
library(purrr)
# oncoprint
library("ComplexHeatmap")
```

```{r, error=F, message=F, results = "hide", warning=F, message=F}
# --- remote
if(!require(CIMICE)){
  devtools::install_github("redsnic/CIMICE-R", subdir = "CIMICE")
  library(CIMICE)
}
# --- local
#library(CIMICE)
```

```{r, context="server"}
# Default example
# genes
dataset <- make.dataset(A,B,C,D) %>%
# samples
  update_df("S1", 0, 0, 0, 1) %>%
  update_df("S2", 1, 0, 0, 0) %>%
  update_df("S3", 1, 0, 0, 0) %>%
  update_df("S4", 1, 0, 0, 1) %>%
  update_df("S5", 1, 1, 0, 1) %>%
  update_df("S6", 1, 1, 0, 1) %>%
  update_df("S7", 1, 0, 1, 1) %>%
  update_df("S8", 1, 1, 0, 1) 

rv <- reactiveValues()
# default values
rv$dataset <- dataset
rv$limitedSize <- FALSE
rv$maxGenes <- 200
rv$maxSamples <- 200
rv$inputMode <- "CAPRI"

update_inputs <- function(){
    if(input$inputTabs == "From Text"){
      rv$dataset <- read.CAPRI.string(input$inputDataset)
    } else if(input$inputTabs == "From File") {
      rv$dataset <- read(input$uploadedFile$datapath)
    }
    rv$limitedSize <- input$limitedSize
    rv$maxGenes <- input$maxGenes
    rv$maxSamples <- input$maxSamples
    rv$inputMode <- input$formatSelect
}


```

```{r}
# format
selectInput(
    "formatSelect",
    label = "Choose input format",
    choices = list(CAPRI = "CAPRI", CAPRIpop = "CAPRIpop")
)
```

#### Input Dataset

```{r, context="server"}
textinputForm <- renderUI({
textAreaInput("inputDataset", "Write here your dataset:", value = 
"
s\\g A B C D
S1 0 0 0 1
S2 1 0 0 0
S3 1 0 0 0
S4 1 0 0 1
S5 1 1 0 1
S6 1 1 0 1
S7 1 0 1 1
S8 1 1 0 1
", resize = "both", rows = 30) %>% shiny::tagAppendAttributes(style = 'width: 100%;')
})
```

```{r}
fileinputForm <- renderUI({
  fileInput("uploadedFile", "Choose File", multiple = FALSE) %>% shiny::tagAppendAttributes(style = 'width: 100%;')
})
```

```{r}
mainPanel(
    tabsetPanel(id = "inputTabs",
        tabPanel("From Text", textinputForm),
        tabPanel("From File", fileinputForm)
    )
) %>% shiny::tagAppendAttributes(style = 'width: 100%;')
```

#### Input Options

```{r}
# feature selection 
checkboxInput("limitedSize", "use custom maximum number of genes/samples (default, unlimited)", value = FALSE) %>% shiny::tagAppendAttributes(style = 'width: 100%;')
numericInput("maxGenes", "Maximum number of genes (3-200)", 20, min=3, max=200) %>% shiny::tagAppendAttributes(style = 'width: 100%;')
numericInput("maxSamples", "Maximum number of samples (3-200)", 20, min=3, max=200) %>% shiny::tagAppendAttributes(style = 'width: 100%;')
# load and run
actionButton("loadData", "Load new dataset") %>% shiny::tagAppendAttributes(style = 'width: 100%;')

observeEvent(input$loadData, { update_inputs() })
```

## Output

```{r}
renderUI({
    mainPanel(
        tabsetPanel(
            tabPanel("visNetwork", rv$vis),
            tabPanel("networkD3", rv$nd3),
            tabPanel("ggraph", rv$gg)
        )
    ) %>% shiny::tagAppendAttributes(style = 'width: 100%;')
})
```

```{r}
# CIMICE logic
reactive({
    # Resize dataset
    dataset <- rv$dataset
    if(rv$limitedSize && rv$inputMode == "CAPRI"){
      n.genes <- rv$maxGenes
      n.samples <- rv$maxSamples
      dataset <- select.samples.on.mutations(dataset , n.samples, desc = F) %>% select.genes.on.mutations(n.genes)
    }
  
    # preprocess input
    samples <- NULL
    freqs   <- NULL
    labels  <- NULL
    genes   <- NULL
    if(rv$inputMode == "CAPRI"){
        # Compact for corrplots
        # update corrplot views
        rv$compacted.dataset <- compact.dataset.easy(dataset) %>% select(-freq)
        # preprocess
        preproc <- dataset.preprocessing(dataset)
        samples <- preproc[["samples"]]
        freqs   <- preproc[["freqs"]]
        labels  <- preproc[["labels"]]
        genes   <- preproc[["genes"]]
    } else if (rv$inputMode == "CAPRIpop"){
        # dataset should be already compacted
        # update corrplot views
        rv$compacted.dataset <- dataset %>% select(-freq)
        # preprocess
        preproc <- dataset.preprocessing.population(dataset)
        samples <- preproc[["samples"]]
        freqs   <- preproc[["freqs"]]
        labels  <- preproc[["labels"]]
        genes   <- preproc[["genes"]]  
    } 
    
    # compute topology and weights
    g <- graph.non.transitive.subset.topology(samples,labels)
    W <- compute.weights.default(g, freqs)
    rv$g <- g
    rv$weights <- W
    rv$labels <- labels
    # prepare output
    rv$gg <- renderPlot({draw.ggraph(rv$g, rv$weights, rv$labels)})
    rv$nd3 <- renderForceNetwork({draw.networkD3(rv$g, rv$weights, rv$labels)})
    rv$vis <- renderVisNetwork({draw.visNetwork(rv$g, rv$weights, rv$labels)})
    
}) 
```

## Dataset analysis

```{r}
renderUI({
    mainPanel(
        tabsetPanel(
            tabPanel("OncoPrint", rv$oncoprint),
            tabPanel("Mutations per gene", rv$mutationspergene),
            tabPanel("Mutations per sample", rv$mutationspersample)
        )
    ) %>% shiny::tagAppendAttributes(style = 'width: 100%;')
})
```


```{r}
reactive({
    rv$oncoprint <- renderPlot({
        m <- matrix(sapply( as.matrix(rv$compacted.dataset), FUN = function (x) if(x==0) " " else "MUT"), 
                    nrow = nrow(rv$compacted.dataset))
      colnames(m)<-colnames(rv$compacted.dataset)
      rownames(m)<-rownames(rv$compacted.dataset)
      oncoPrint(m, show_column_names = TRUE)
    })
    rv$mutationspergene <- renderPlot({
        gene.mutations.hist(rv$dataset)
    })  
    rv$mutationspersample <- renderPlot({
        sample.mutations.hist(rv$dataset, binwidth = 1)
    })  
})
```

## Correlation plots

```{r}
renderUI({
    mainPanel(
        tabsetPanel(
            tabPanel("Gene Based", rv$corrplotgene),
            tabPanel("Sample Based", rv$corrplotsample)
        )
    ) %>% shiny::tagAppendAttributes(style = 'width: 100%;')
})
```

```{r}
reactive({
    rv$corrplotgene <- renderPlot({
        dataset <- rv$compacted.dataset
        corrplot.genes(dataset)
    })
    
    rv$corrplotsample <- renderPlot({
        dataset <- rv$compacted.dataset
        corrplot.samples(dataset)
    })
})
```

```{r}
#run all
```



